Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/12/2023
Var
// Seção de Declarações das variáveis 
final : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
final <- 1738
escreval("1 milãa,7 centenas,3 dezenas,8 unidade")

Fimalgoritmo